# Generated by Django 4.2.7 on 2023-11-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('category_1', models.CharField(max_length=100)),
                ('category_2', models.CharField(max_length=100)),
                ('category_3', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('attribute_1', models.CharField(default='', max_length=20)),
                ('attribute_2', models.CharField(default='', max_length=20)),
                ('attribute_3', models.CharField(default='', max_length=20)),
                ('retail_price', models.FloatField(default=0.0)),
                ('branch_price', models.FloatField(default=0.0)),
                ('cost_price', models.FloatField(default=0.0)),
                ('supplier_name', models.CharField(default='', max_length=20)),
                ('backorder_qty', models.IntegerField(default=0)),
                ('stock_available', models.IntegerField(default=0)),
            ],
        ),
    ]
